### ISSUE TITLE
Indents need in the Create Task screen 

### ISSUE THREAD

**Issue by jli724** [StevenPG/ProjectManagement#108]
Indent the procreated words in  task name, task description, and project name field.

**Comment by Firesnake38** [comment]
Adding the needed padding

**Comment by jli724** [comment]
when you create a task. Its the prefilled words in the fields

**Comment by StevenPG** [comment]
@jli724 and I didn't get to adequately explain. The padding was a step in the right direction, so I finished it off really quick. Remind me to explain what I mean, but this issue is closed in pull request #120 (woo!)
