### ISSUE TITLE
Task with two or more words wont update

### ISSUE THREAD

**Issue by jli724** [StevenPG/ProjectManagement#122]
Task will not update as complete when moving the percentage bar of a task that is named with more than one word.

**Comment by StevenPG** [comment]
Figured out the issue,

To set the SQL statement to be a valid statement, I run this line of python:
[code]
updateString = request.args.get('updatestring').replace("_", " ")
[/code]

This causes the task name to actually have a space in it, whereas in the database we give it an underscore.

**Comment by StevenPG** [comment]
I'm going to attempt to fix it by making things with spaces in the database concatenated with a - instead. This way we can remove the dash instead of the underscore when displaying.
