### ISSUE TITLE
alert user which screen they are in 

### ISSUE THREAD

**Issue by hrichiez** [StevenPG/ProjectManagement#53]
everytime a user navagate to screen in the app they should know in which screen they are.

**Comment by Firesnake38** [comment]
Complete for 95% of screens

**Comment by StevenPG** [comment]
On friday, @Firesnake38 let's finish adding those last 5% and then we can close this issue.

**Comment by StevenPG** [comment]
Hector and Tyler finished this up a few weeks ago
