### ISSUE TITLE
password encryption

### ISSUE THREAD

**Issue by hrichiez** [StevenPG/ProjectManagement#55]
the password should be saved in the database in a encrypted format.

**Comment by StevenPG** [comment]
I think I am going to push off this issue until later in the semester. I only want to make this apparent because it isn't in the list of features. I also will have to write a few wrapper classes to make this an easy transition from the current implementation.

**Comment by hrichiez** [comment]
I have an idea of how to solve this problem in a simple way. why don’t we convert the password into ACII code and sent the converted string which will be number to the database and when getting the password back from the database we reverse the characters back to the string it was. We could use that simple encryption with not too much coding to implement.
On Mar 8, 2016, at 8:13 PM, Steven Gantz <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I am going to push off this issue until later in the semester. I only want to make this apparent because it isn't in the list of features. I also will have to write a few wrapper classes to make this an easy transition from the current implementation.

**Comment by StevenPG** [comment]
Thats perfect, I was definitely overthinking it. We really just need to NOT use plaintext. Do you want to complete it Hector? Just write a class that can do the conversions (so we don't need to copy and paste code).

It's not like it needs to be done soon regardless. If you would like to implement it, just switch over the assignee to yourself. I'm going to take a look at banging out some of the issues at the start of this week.

**Comment by hrichiez** [comment]
no problem I would have no problem creating the class. I probably start working on it soon.
On Mar 10, 2016, at 1:33 PM, Steven Gantz <notifications@github.com<mailto:notifications@github.com>> wrote:


Thats perfect, I was definitely overthinking it. We really just need to NOT use plaintext. Do you want to complete it Hector? Just write a class that can do the conversions (so we don't need to copy and paste code).

It's not like it needs to be done soon regardless. If you would like to implement it, just switch over the assignee to yourself. I'm going to take a look at banging out some of the issues at the start of this week.

**Comment by hrichiez** [comment]
implemented coding to encrypt users password which is saved in the database. Steven I assigned this task to you so you can take a look at it and make sure it is working appropriately.

**Comment by StevenPG** [comment]
It doesn't seem to be working. It sets every value to the number 32. I am investigating currently.

**Comment by StevenPG** [comment]
I think you might have missed a line of code, I simplified it to: 

`
char character = ' ';
    String str;

    public String encrypt(String password) {

        StringBuilder sb = new StringBuilder();
        // loop through each character in the password
        // assigns it to the stringbuilder in ascii form
        // and save the whole number in a integer
        for (int j = 0; j < password.length(); j++)
            sb.append((int) character);

        return sb.toString();

    }`

You are only appending the space character to the StringBuilder. I'll just add the missing line and verify the fix works. We can consider this completed.

**Comment by StevenPG** [comment]
Completed and working!
