### ISSUE TITLE
Design on createTask screen

### ISSUE THREAD

**Issue by StevenPG** [StevenPG/ProjectManagement#80]
The design is currently broken on my device. 

The create button no longer appears and this breaks functionality.

 Hopefully @Firesnake38 or @hrichiez can take a look at it in the coming days.

You can add this as a bug @jli724.

(Whoever makes the fix, merge your working branch as soon as possible. For FR12 and FR5 I need to verify tasks are created successfully.)

**Comment by StevenPG** [comment]
As soon as this is merged into the main branch, @hrichiez feel free to close this issue.

**Comment by hrichiez** [comment]
create task screen has been fixed to handle the creation of task and assigning it to a user
