### ISSUE TITLE
Need to reset database to clean slate to test using real emails and encryption

### ISSUE THREAD

**Issue by StevenPG** [StevenPG/ProjectManagement#85]
Because our original accounts use our email addresses, and they use the unencrypted passwords, we are unable to access them right now. I was able to verify that adding a member works successfully, but moving forward, we need easy access to valid email accounts that have the new encrypted passwords.

When you get a chance @Firesnake38 , wipe the entire database of entries. We will each create our accounts as needed moving forward.

**Comment by Firesnake38** [comment]
Done and in the tyler folder on your server
