### ISSUE TITLE
Figure out which activities should be removed from activity stack

### ISSUE THREAD

**Issue by StevenPG** [StevenPG/ProjectManagement#88]
You can set the android:noHistory tag in these activities, allowing for them to never be navigated to using the back button. This would remove any issues that stem from stuff like:

Create issue - > back to create issue -> back to task list -> back to main menu

etc.

@Firesnake38 - Could you mark which activities this would make the most sense for? We can implement this easily before the end of the first sprint.

**Comment by Firesnake38** [comment]
Hey Steve, I'm assuming the activities that don't need the back button would be:
Create Task
Create Project
Submit Task
Profile
Tutorial (Depending On Whether Or Not We Have This)

Where exactly do I add the android:noHistory="true" tag? Is it just in the first tag of the xml file?

**Comment by StevenPG** [comment]
Its in the android manifest with the other android: stuff

**Comment by Firesnake38** [comment]
I have added the android:noHistory="true" is certain places I will have to test it further to see if i put in the right files

**Comment by StevenPG** [comment]
It seems like it is working, I ran through the code and the files. If we come across a bug we can list it in a new issue.
